<Project>
    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/SzymonFrac/FileCompositions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
	
    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>