<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Quality\Ownership\Extensions\" />
    <Folder Include="ResourceSchema\File\Registrar\" />
    <Folder Include="ResourceSchema\File\Register\" />
    <Folder Include="Validation\Handler\Specialized\" />

	<InternalsVisibleTo Include="FileCompositions.Core.Database" />
	<InternalsVisibleTo Include="FileCompositions.Extensions" />
  </ItemGroup>

</Project>
