<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FileSystem\**" />
    <Compile Remove="File\Operator\**" />
    <EmbeddedResource Remove="FileSystem\**" />
    <EmbeddedResource Remove="File\Operator\**" />
    <None Remove="FileSystem\**" />
    <None Remove="File\Operator\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Dll\Default.dll" />
  </ItemGroup>

  <ItemGroup>

	<InternalsVisibleTo Include="FileCompositions.Core.Database" />
	<InternalsVisibleTo Include="FileCompositions.Hosting" />
	<InternalsVisibleTo Include="FileCompositions.Hosting.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileCompositions.Core.FileSystem\FileCompositions.Core.FileSystem.csproj" />
  </ItemGroup>

</Project>
