<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Host\Schema\Resources\**" />
    <Compile Remove="Host\Schema\Setting\**" />
    <EmbeddedResource Remove="Host\Schema\Resources\**" />
    <EmbeddedResource Remove="Host\Schema\Setting\**" />
    <None Remove="Host\Schema\Resources\**" />
    <None Remove="Host\Schema\Setting\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileCompositions.Core\FileCompositions.Core.csproj" />

	<InternalsVisibleTo Include="FileCompositions.Hosting.EntityFrameworkCore" />
  </ItemGroup>

</Project>
