<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileCompositions.Core.Database\FileCompositions.Core.Database.csproj" />
    <ProjectReference Include="..\FileCompositions.Core\FileCompositions.Core.csproj" />
    <ProjectReference Include="..\FileCompositions.Extensions\FileCompositions.Extensions.csproj" />
  </ItemGroup>

</Project>
