name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: |
          dotnet build \
            --configuration Release \
            --no-restore \
            -p:ContinuousIntegrationBuild=true

      - name: Pack
        run: |
          dotnet pack \
            --configuration Release \
            --no-build \
            -p:PackageVersion=${GITHUB_REF_NAME#v} \
            -o ./artifacts/packages

      - name: Authenticate with NuGet
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ github.actor }}

      - name: Publish packages
        run: |
          dotnet nuget push "./artifacts/packages/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --skip-duplicate
